apiVersion: v1
kind: Service
metadata:
    name: web
spec:
    ports:
        -   port: 9000
            targetPort: 9000
            protocol: TCP
            name: http
    selector:
        app: fpm

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: db-pv-volume
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/keep-db-pv-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: keep-db-pv-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fpm
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fpm
    template:
        metadata:
            labels:
                app: fpm
        spec:
            initContainers:
                -   name: volume-permission
                    image: alpine
                    securityContext:
                        runAsUser: 0
                    volumeMounts:
                        -   name: keep-db-persistent-storage
                            mountPath: /vol1
                    command:
                        - sh
                        - -c
                        - chown -R 82:82 /vol1
            containers:
                -   name: fpm
                    image: docker.pkg.github.com/qwertys318/keep-nodes-dashboard/fpm:0.1.4
                    ports: [{containerPort: 9000}]
                    volumeMounts:
                        -   name: keep-db-persistent-storage
                            mountPath: /var/www/html/var/db
                    command:
                        - sh
                        - -c
                        - |
                          php ./html/bin/console doctrine:database:create --no-interaction
                          php ./bin/console doctrine:migrations:migrate --no-interaction
                          php-fpm
            imagePullSecrets:
                -   name: github-registry
            volumes:
                -   name: keep-db-persistent-storage
                    persistentVolumeClaim:
                        claimName: keep-db-pv-claim