index:
    path: /
    controller: App\Controller\IndexController::index
node.add:
    path: /crud/node
    methods: [POST]
    controller: App\Controller\IndexController::addNode
node.list:
    path: /crud/node
    methods: [GET]
    controller: App\Controller\IndexController::nodeList
