name: Docker

on:
  push:
    tags:
      - v*
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: web

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: |
          apt -y install php php-json php-bcmath php-gd php-zip
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm -f composer-setup.php
          pwd
          ls -lah

